import type { Lead } from "@/lib/gemini";

// Realistic mock leads for animation demonstration
export const MOCK_LEADS: Lead[] = [
  {
    _id: "1",
    company_name: "TechVision Analytics",
    contact_person: "Sarah Chen",
    job_title: "VP of Growth",
    email: "sarah.chen@techvision.com",
    phone: "+1 (415) 555-0142",
    website: "techvision.io",
    company_size: "51-200",
    annual_revenue: "$5M-$10M",
    funding_stage: "Series B",
    tech_stack: ["React", "Node.js", "AWS", "PostgreSQL"],
    linkedin_url: "https://linkedin.com/company/techvision",
    quality_score: 89,
    intent_signals: ["Downloaded pricing guide", "Attended webinar", "Viewed pricing page 3x"],
    tags: ["High Intent", "Fast Growing", "Tech Stack Match"],
    pain_point: "Scaling data infrastructure",
    outreach_hook: "Hi Sarah, saw TechVision is scaling their analytics platform. Our solution helped similar companies reduce data latency by 60%—happy to share case studies.",
    best_contact_time: "Tuesday 2-4 PM",
  },
  {
    _id: "2",
    company_name: "CloudScale Ventures",
    contact_person: "Michael Rodriguez",
    job_title: "CTO",
    email: "m.rodriguez@cloudscale.io",
    phone: "+1 (650) 555-0183",
    website: "cloudscale.io",
    company_size: "201-500",
    annual_revenue: "$10M-$25M",
    funding_stage: "Series C",
    tech_stack: ["TypeScript", "Kubernetes", "GCP", "Redis"],
    linkedin_url: "https://linkedin.com/company/cloudscale",
    quality_score: 92,
    intent_signals: ["Visited pricing 5x", "Engaged with demo video", "Downloaded ROI calculator"],
    tags: ["Perfect Fit", "Enterprise", "Decision Maker"],
    pain_point: "Microservices orchestration",
    outreach_hook: "Michael, CloudScale's architecture aligns perfectly with our Kubernetes optimization tools. Let's chat about how we're helping enterprises cut infrastructure costs by 40%.",
    best_contact_time: "Wednesday 10 AM-12 PM",
  },
  {
    _id: "3",
    company_name: "DataFlow Systems",
    contact_person: "Jessica Morrison",
    job_title: "Director of Engineering",
    email: "jess.morrison@dataflow.systems",
    phone: "+1 (212) 555-0127",
    website: "dataflow.systems",
    company_size: "101-250",
    annual_revenue: "$2M-$5M",
    funding_stage: "Series A",
    tech_stack: ["Python", "Apache Spark", "Docker", "MySQL"],
    linkedin_url: "https://linkedin.com/company/dataflow",
    quality_score: 85,
    intent_signals: ["Opened 4 emails", "Visited careers page", "Joined community Slack"],
    tags: ["Growing Interest", "Tech Savvy", "Early Stage"],
    pain_point: "Data pipeline bottlenecks",
    outreach_hook: "Jessica, noticed DataFlow is expanding their engineering team. We specialize in data pipeline optimization—helped similar companies reduce processing time by 50%. Worth a quick call?",
    best_contact_time: "Monday 3-5 PM",
  },
  {
    _id: "4",
    company_name: "InnovateLabs Inc",
    contact_person: "David Thompson",
    job_title: "Head of Product",
    email: "d.thompson@innovatelabs.com",
    phone: "+1 (510) 555-0194",
    website: "innovatelabs.com",
    company_size: "251-500",
    annual_revenue: "$15M-$30M",
    funding_stage: "Series B",
    tech_stack: ["Vue.js", "Django", "MongoDB", "Firebase"],
    linkedin_url: "https://linkedin.com/company/innovatelabs",
    quality_score: 88,
    intent_signals: ["Downloaded whitepaper", "Attended product demo", "Shared with team (4 people)"],
    tags: ["Hot Lead", "Team Interest", "Budget Available"],
    pain_point: "User onboarding optimization",
    outreach_hook: "David, InnovateLabs' growth is impressive. Our product personalization engine helped similar SaaS companies increase onboarding completion by 65%. Curious if that's a priority?",
    best_contact_time: "Thursday 2-4 PM",
  },
  {
    _id: "5",
    company_name: "FutureScale Tech",
    contact_person: "Emily Wang",
    job_title: "VP of Operations",
    email: "emily.wang@futurescript.io",
    phone: "+1 (408) 555-0161",
    website: "futurescript.io",
    company_size: "501-1000",
    annual_revenue: "$50M+",
    funding_stage: "Series D",
    tech_stack: ["Java", "Spring Boot", "Oracle", "Kubernetes"],
    linkedin_url: "https://linkedin.com/company/futurescript",
    quality_score: 94,
    intent_signals: ["Strategic partner inquiry", "Attended enterprise conference", "Peer referral"],
    tags: ["Strategic Fit", "Enterprise Buyer", "High Value"],
    pain_point: "Enterprise system integration",
    outreach_hook: "Emily, FutureScale's expansion into enterprise markets aligns with what we do. We're helping Fortune 500 companies streamline system integration—would love to share insights.",
    best_contact_time: "Tuesday 11 AM-1 PM",
  },
  {
    _id: "6",
    company_name: "NexGen Dynamics",
    contact_person: "James Park",
    job_title: "Founder & CEO",
    email: "james@nexgendyn.com",
    phone: "+1 (415) 555-0128",
    website: "nexgendyn.com",
    company_size: "11-50",
    annual_revenue: "$500K-$1M",
    funding_stage: "Pre-Seed",
    tech_stack: ["Next.js", "FastAPI", "Supabase", "Vercel"],
    linkedin_url: "https://linkedin.com/company/nexgendyn",
    quality_score: 76,
    intent_signals: ["Signed up for trial", "Watched tutorial", "Asked support questions"],
    tags: ["Startup", "Growing Usage", "Trial Active"],
    pain_point: "Rapid product development",
    outreach_hook: "James, NexGen is building some cool things fast. We help early-stage companies scale infrastructure without headcount. Might be worth exploring.",
    best_contact_time: "Friday 1-3 PM",
  },
  {
    _id: "7",
    company_name: "StrategyCore Partners",
    contact_person: "Amanda Foster",
    job_title: "Managing Director",
    email: "a.foster@strategycore.com",
    phone: "+1 (646) 555-0145",
    website: "strategycore.com",
    company_size: "51-100",
    annual_revenue: "$3M-$7M",
    funding_stage: "Bootstrapped",
    tech_stack: ["Python", "Tableau", "Salesforce", "Excel"],
    linkedin_url: "https://linkedin.com/company/strategycore",
    quality_score: 72,
    intent_signals: ["Attended industry event", "Read blog post", "Bookmarked resources"],
    tags: ["Consulting Firm", "Data-Driven", "Decision Pending"],
    pain_point: "Client data analysis",
    outreach_hook: "Amanda, StrategyCore's consulting focus on data strategy is interesting. We help firms like yours cut analysis time by 70%—worth a quick 15-min chat?",
    best_contact_time: "Monday 2-4 PM",
  },
  {
    _id: "8",
    company_name: "OptiFlow Solutions",
    contact_person: "Robert Chen",
    job_title: "VP of Sales",
    email: "r.chen@optiflow.co",
    phone: "+1 (503) 555-0176",
    website: "optiflow.co",
    company_size: "201-1000",
    annual_revenue: "$20M-$50M",
    funding_stage: "Series C",
    tech_stack: ["C++", "Go", "Kubernetes", "Prometheus"],
    linkedin_url: "https://linkedin.com/company/optiflow",
    quality_score: 91,
    intent_signals: ["Downloaded case studies", "Viewed demo multiple times", "Forwarded to procurement"],
    tags: ["High Intent", "Multiple Stakeholders", "Budget Allocated"],
    pain_point: "System performance optimization",
    outreach_hook: "Robert, OptiFlow's performance optimization needs match what we do perfectly. We helped similar companies reduce system latency by 55%—have a 15 min to discuss?",
    best_contact_time: "Wednesday 10 AM-12 PM",
  },
];
